#Designed to run and manage FracVal runs. Will create a folder "fname<variablevalue>" and 
#store the aggregates generated for a range of values of that variable generated by seq()

#Must be run in the same folder as the FracVal code.

#Select Directory to run in
wd_fold="C:/Users/padmer/OneDrive - KI.SE/R_CDA/FracVAL/PROGRAM_source_codes/test"

setwd(wd_fold)

#Define range of variable to be tested here it's number of particles per agglomerate
variable=seq(1.2,2.4,0.2)

#Define common name stem of output folders for aggregates
fname="Dfvals"

#Create compilation script
compilation_bat=c("gfortran Frac_VAL_CCA.f90 ctes.f90 CCA_module.f90 PCA_cca.f90 PCA_Subclusters_module.f90 RAND_SAMPLE.f90 random.f90 a_Random_PP.f90 Save_results_CC.f90 -o FRACVAL_CCA_executable.exe",
"gfortran Frac_VAL_CCA.f90 ctes.f90 CCA_module.f90 PCA_cca.f90 PCA_Subclusters_module.f90 RAND_SAMPLE.f90 random.f90 a_Random_PP.f90 Save_results_CC.f90 -o FRACVAL_CCA_executable.exe",
"copy NUL EmptyFile.txt")

f_conn=file('Compilation.bat')
writeLines(compilation_bat,f_conn)
close(f_Conn)


#Loop over variable range

for (i in variable){

#Set the appropriate quantity to be tested to i

#Number of particles per aggregate
numpart=100
#Fractal dimension of aggregates generated
Df=i
#Fractal prefactor of aggregates generated
kf=1.3
#Geometric mean of aggregate primary particle size in nanometres
rp_g=16
#Geometric standard deviation of aggregate primary particle size
rp_gstd=1.2
#Quantity of aggregates to generate
quant_agg=20

#Keep at below or below 0.1 increase only if "PC is not able to work message is displayed"
Subclsiz=0.1

#Erase file before writing just in case
unlink("ctes.f90")

#Create the input file for FracVal to compile
fileConn<-file("ctes.f90")
text=c("module ctes",
"    implicit none",
paste("    integer, parameter:: N=",numpart,"                           !Number of PP",sep=""),
paste("    real, parameter:: Df=",Df,"                            !Fractal dimension",sep=""),
paste("    real, parameter:: kf=",kf,"                            !Fractal prefactor",sep=""),
paste("    real, parameter:: rp_g=",rp_g,"                          !Geometric mean PP",sep=""),
paste("    real, parameter:: rp_gstd=",rp_gstd,"                       !Geometric PP standard deviation",sep=""),
paste("    integer, parameter:: Quantity_aggregates=",quant_agg,"        !Quantity of aggregates to be generated",sep=""),
"    integer, parameter:: Ext_case= 0                    !Activate extreme cases",
paste("    real, parameter:: Nsubcl_perc=",Subclsiz,"                  !controls the subclusters size (keep always in 10%, only increase when PC is not able to work)",sep=""),
"    real, parameter:: tol_ov=10.**(-3.)                  !Tolerance to overlapping",
"    real, parameter :: pi=4.0*atan(1.0)",
"    real R(N)                                            !Primary particles radii and mass",
"    real X(N), Y(N), Z(N)                                !Coordinates of primary particles",
"    integer:: iter, i, j, k",
"end module ctes")


writeLines(text,fileConn)

close(fileConn)

#Helps to give a little time for everything to work together
Sys.sleep(1)

unlink("EmptyFile.txt")

#Run the compilation script
shell.exec("Compilation.bat")
cont=1
Sys.sleep(0.2)

#Compilation script should output "EmptyFile.txt" wait until it exists
while(!file.exists("EmptyFile.txt")){
  Sys.sleep(0.2)
}

#Create output dir and run executable
dir.create("RESULTS")
shell.exec("FRACVAL_CCA_executable.exe")

#Wait until all aggregates have been generated
while(length(list.files("RESULTS\\"))<quant_agg){
  Sys.sleep(0.2)
}

#Move RESULTS to a new directory and copy parameter file there also
dirname=paste(paste(fname,"_",sep=""),i)
file.rename("RESULTS",dirname)
file.copy("ctes.f90",paste(dirname,"\\ctes.f90",sep=""))

#Cleanup files
unlink("FRACVAL_CCA_executable.exe")
unlink("EmptyFile.txt")
unlink("RESULTS/*")
}
